application:
  host: "127.0.0.1"
  port: 8000
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "1g7x3@freesourcecodes.com"
  authorization_token: "bfb6a3d6-3873-4f01-9600-4b822f6e579b"
  timeout_milliseconds: 10000
